#!/bin/bash
if [ -e check_mine.txt ]; then
	rm check_mine.txt
fi
if [ -e check_expected.txt ]; then
	rm check_expected.txt
fi

for file in $(ls ./)
do
 	if [ "${file##*.}" = "cl" ]; then
		../../../bin/lexer ${file} | ../../../bin/parser ${file} | ../semant ${file} > check_mine.txt 2>&1
		../../../bin/lexer ${file} | ../../../bin/parser ${file} | ../../../bin/semant ${file} > check_expected.txt 2>&1

		result=$(diff check_mine.txt check_expected.txt)

		if [ -z "$result" ]; then
			echo "passed"
		else
			echo "$result"
		fi
	fi

done
