#!/bin/bash
if [ -e check_mine.txt ]; then 
  rm check_mine.txt 
fi
if [ -e check_expected.txt ]; then 
  rm check_expected.txt 
fi


for file in $(ls ./)
do 
  if [ "${file##*.}" = "cl" ]; then
      ../../bin/lexer ${file} | ./parser > check_mine.txt 2>&1
      ../../bin/lexer ${file} | ../../bin/parser > check_expected.txt 2>&1
      
      result=$(diff check_mine.txt check_expected.txt)

      if [ -z "$result" ]; then 
        echo "${file} passed"
      else 
        echo -e "${file}\n$result"
      fi

  fi
  

done

